despesas/config/routes.rb
Despesas::Application.routes.draw do
  resources :bills

  resources :responsibles

  get "welcome/index"

  root 'welcome#index'

  resources :responsibles do
  	resources :bills
  end

  

end

despesas/app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :responsible

end

despesas/app/models/responsible.rb
class Responsible < ActiveRecord::Base
	has_many :bills
	validates :name, presence: true
	validates :email, presence: true			
end

despesas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

despesas/app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
	@responsibles = Responsible.all
	if params[:responsibles] != "" && params[:responsibles] != nil
		@responsible = Responsible.find(params[:responsibles])
	end			
  end
  
  def list
	@bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
	@responsibles = Responsible.all
  end

  # GET /bills/1/edit
  def edit
	@responsibles = Responsible.all
  end

  # POST /bills
  # POST /bills.json
  def create
	@responsible = Responsible.find(params[:bill][:responsible])
	@responsible.bills.create(params[:bill].permit(:date, :description, :value))
	@bill = Bill.new(bill_params)
	
	respond_to do |format|
		format.html { redirect_to @bill, notice: 'Despesa criada com sucesso' }
		format.json { render action: 'show', status: :created, location: @bill }			
	end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Despesa editada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:date, :description, :value, :responsible_id)
    end
end

despesas/app/controllers/responsibles_controller.rb
class ResponsiblesController < ApplicationController
  before_action :set_responsible, only: [:show, :edit, :update, :destroy]

  # GET /responsibles
  # GET /responsibles.json
  def index
    @responsibles = Responsible.all
  end

  # GET /responsibles/1
  # GET /responsibles/1.json
  def show
  end

  # GET /responsibles/new
  def new
    @responsible = Responsible.new
  end

  # GET /responsibles/1/edit
  def edit
  end

  # POST /responsibles
  # POST /responsibles.json
  def create
    @responsible = Responsible.new(responsible_params)

    respond_to do |format|
      if @responsible.save
        format.html { redirect_to @responsible, notice: 'Responsavel criado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @responsible }
      else
        format.html { render action: 'new' }
        format.json { render json: @responsible.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responsibles/1
  # PATCH/PUT /responsibles/1.json
  def update
    respond_to do |format|
      if @responsible.update(responsible_params)
        format.html { redirect_to @responsible, notice: 'Responsavel editado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @responsible.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsibles/1
  # DELETE /responsibles/1.json
  def destroy
	@responsible.bills.each do |bill|
		bill.destroy
	end
    @responsible.destroy
    respond_to do |format|
      format.html { redirect_to responsibles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_responsible
      @responsible = Responsible.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def responsible_params
      params.require(:responsible).permit(:name, :email)
    end
end

despesas/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

despesas/app/helpers/application_helper.rb
module ApplicationHelper
end

despesas/app/helpers/bills_helper.rb
module BillsHelper
end

despesas/app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

despesas/app/helpers/welcome_helper.rb
module WelcomeHelper
end

despesas/app/views/bills/_filter.html.erb
<div>
	<%= form_tag('/bills', method: :get) do %>
		<% vetName = [['-- Selecione --', ""]] %>
		<% @responsibles.each do |res| %>
		<% vetName << [res.name, res.id] %>
		<% end %>
		<div class="field">
			<%= label_tag 'Responsavel' %> <br><br>
			<%= select_tag "responsibles", options_for_select(vetName), class: 'combo' %>	
		</div>
		<div class="periodo">
			<%= label_tag 'Periodo' %> <br><br>
			<%= label_tag 'De' %>
			<%= date_field_tag 'dateBegin' %>
			<div style="position: relative; top:-28px; left: 235px;">
				<%= label_tag 'Ate' %>
				<%= date_field_tag 'dateEnd' %> <br><br>
				<div style="position: relative; left: 117px;"><%= button_tag "Filtrar", class: 'btn' %></div>
			</div>
		</div>
	<% end %>
</div>

despesas/app/views/bills/_form.html.erb
<script>
function validatesForm() {
	responsible = document.getElementById('bill_responsible').value;
	description = document.getElementById('bill_description').value;
	value = document.getElementById('bill_value').value;
	message = "";
	
	if (responsible == "") {
		message += "Cadastre um responsavel \n";
	}	
	
	if (description == "") {
		message += "Preencha o campo Descricao \n";
		document.getElementById('bill_description').focus();
	}

	if (value == "") {
		message += "Preencha o campo Valor \n";
		document.getElementById('bill_value').focus();
	}

	if (value != "" && isNaN(value)) {
		message += "Digite um numero inteiro ou real no campo Valor";
		document.getElementById('bill_value').focus();
	}


	if (message == "") {
		return true;
	} else {
		alert(message);
		return false;
	}
}
</script>

<%= form_for(@bill, :html => {:onsubmit => "return validatesForm()"}) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% vetName = [] %>
  <% @responsibles.each do |res| %>
  <% vetName << [res.name, res.id] %>
  <% end %>  
 
  <div class="field">
    <%= f.label :responsible, "Responsavel" %><br>
    <%= f.select :responsible, options_for_select(vetName) %>
  </div>		
 
  <div class="field">
    <%= f.label :date, "Data" %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description, "Descricao" %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :value, "Valor" %><br>
    <%= f.text_field :value, class: 'text' %>
  </div>
  <div class="actions">
	<br>
    <%= f.submit "Salvar", class: 'btn' %>
  </div>
<% end %>

despesas/app/views/bills/_tablerow.html.erb
<tr>
	<td><%= bill.date.strftime("%d/%m/%Y") %></td>
	<td><%= bill.responsible.name %></td>
	<td><%= bill.description %></td>
	<td><font>R$ </font><%= number_with_precision(bill.value, precision: 2) %></td>
	<td><%= link_to 'Exibir', bill %></td>
	<td><%= link_to 'Editar', edit_bill_path(bill) %></td>
	<td><%= link_to 'Excluir', bill, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
</tr>

despesas/app/views/bills/edit.html.erb
<script>
function validatesForm() {
	description = document.getElementById('bill_description').value;
	value = document.getElementById('bill_value').value;
	message = "";
	if (description == "") {
		message += "Preencha o campo Descricao \n";
		document.getElementById('bill_description').focus();
	}

	if (value == "") {
		message += "Preencha o campo Valor \n";
		document.getElementById('bill_value').focus();
	}

	if (value != "" && isNaN(value)) {
		message += "Digite um numero inteiro ou real no campo Valor";
		document.getElementById('bill_value').focus();
	}


	if (message == "") {
		return true;
	} else {
		alert(message);
		return false;
	}
}
</script>

<h1>Editando Despesa</h1>

<%= form_for(@bill, :html => {:onsubmit => "return validatesForm()"}) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>	
 
  <div class="field">
    <%= f.label :date, "Data" %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description, "Descricao" %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :value, "Valor" %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar", class: 'btn' %>
  </div>
<% end %>

<%= link_to 'Exibir', @bill %> |
<%= link_to 'Voltar', bills_path %>

despesas/app/views/bills/index.html.erb
<h1>Listar despesas</h1>

<%= render 'filter'  %>

<% if params[:dateBegin] != nil && params[:dateEnd] != nil && params[:dateBegin] != '' && params[:dateEnd] != '' %>
	<% dateBegin = Date.parse(params[:dateBegin]) %>
	<% dateEnd = Date.parse(params[:dateEnd]) %>
<% end %>

<div>
<% if !@bills.empty? %>
	<div class="tabela">
	<table border>
	  <thead>
	    <tr align='left'>
	      <th>Data</th>
		  <th>Responsavel</th>
	      <th>Descricao</th>
	      <th>Valor</th>
	      <th></th>
	      <th></th>
	      <th></th>
	    </tr>
	  </thead>

	  <tbody>
		<% valorTotal = 0.0 %>
	    <% @bills.each do |bill| %>
			<% if @responsible == nil && dateBegin == nil && dateEnd == nil %>
			 	<%= render :partial => 'tablerow', :locals => {:bill => bill} %>
				<% valorTotal += bill.value %>
			<% else %>
				<% if @responsible != nil && dateBegin == nil && dateEnd == nil %>
					<% if @responsible == bill.responsible %>	
						<%= render :partial => 'tablerow', :locals => {:bill => bill} %>
						<% valorTotal += bill.value %>
					<% end %>
				<% else %>
					<% if @responsible == nil && dateBegin != nil && dateEnd != nil %>
						<% if dateBegin <= bill.date && dateEnd >= bill.date %>
							<%= render :partial => 'tablerow', :locals => {:bill => bill} %>
							<% valorTotal += bill.value %>						
						<% end %>
					<% else %>
						<% if @responsible != nil && dateBegin != nil && dateEnd != nil %>
							<% if @responsible == bill.responsible && dateBegin <= bill.date && dateEnd >= bill.date %>
								<%= render :partial => 'tablerow', :locals => {:bill => bill} %>
								<% valorTotal += bill.value %>				
							<% end %>
						<% end %>
					<% end %>    
				<% end %>  
			<% end %>
		<% end %>
	  </tbody>
	</table>
	<br>

	<h2>Total: R$ <%= number_with_precision(valorTotal, precision: 2) %></h2>
	</div>
<% else %>
	<div class="tabela"><h2>Nao foi encontrada nenhuma despesa</h1></div>
<% end %>

<br>
<div class="links">
	<%= link_to 'Adicionar Despesa', new_bill_path %> &nbsp
	<%= link_to 'Voltar ao inicio', root_path %>
</div>
</div>

despesas/app/views/bills/new.html.erb
<h1>Nova Despesa</h1>
<br>
<%= render 'form' %>

<%= link_to 'Voltar', bills_path %>

despesas/app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @bill.date.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Responsavel:</strong>
  <%= @bill.responsible.name %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @bill.description %>
</p>

<p>
  <strong>Valor:</strong>
  <font> R$ <%= number_with_precision(@bill.value, precision: 2) %></font>
</p>

<%= link_to 'Editar', edit_bill_path(@bill) %> |
<%= link_to 'Voltar', bills_path %>

despesas/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Despesas</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

despesas/app/views/responsibles/_form.html.erb
<script>
function validatesForm() {
	name = document.getElementById('responsible_name').value;
	email = document.getElementById('responsible_email').value;
	message = "";
	if (name == "") {
		message += "Preencha o campo Nome \n";
		document.getElementById('responsible_name').focus();
	}		
	
	if (email == "") {
		message += "Preencha o campo E-mail \n";
		document.getElementById('responsible_email').focus();
	}	

	if (email != "" && email.indexOf('@') == -1) {
		message += "Digite um e-mail valido";
		document.getElementById('responsible_email').focus();
	}
	
	if (message == "") {
		return true;	
	} else {
		alert(message);
		return false;
	}
}
</script>

<%= form_for(@responsible, :html => {:onsubmit => "return validatesForm()"}) do |f| %>
  <% if @responsible.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@responsible.errors.count, "erro") %> impediram o cadastro:</h2>
      <ul>
      <% @responsible.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name, "Nome" %><br>
    <%= f.text_field :name, class: 'text' %>
  </div>
  <br>
  <div class="field">
    <%= f.label :email, "E-mail" %><br>
    <%= f.text_field :email, class: 'text' %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar", class: 'btn' %>
  </div>
<% end %>

despesas/app/views/responsibles/edit.html.erb
<h1>Editando Responsavel</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @responsible %> |
<%= link_to 'Voltar', responsibles_path %>

despesas/app/views/responsibles/index.html.erb
<h1>Lista de Responsaveis</h1>

<% if !@responsibles.empty? %>

<table border>
  <thead>
    <tr align="left">
      <th>Nome</th>
      <th>E-mail</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @responsibles.each do |responsible| %>
      <tr>
        <td><%= responsible.name %></td>
        <td><%= responsible.email %></td>
        <td><%= link_to 'Exibir', responsible %></td>
        <td><%= link_to 'Editar', edit_responsible_path(responsible) %></td>
        <td><%= link_to 'Excluir', responsible, method: :delete, data: { confirm: 'Isso ira deletar as despesas dele tambem. Deseja mesmo excluir o responsavel?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
<h2>Nao ha responsaveis cadastrados</h2>
<% end %>

<br>

<%= link_to 'Adicionar Responsavel', new_responsible_path %> &nbsp
<%= link_to 'Voltar ao inicio', root_path %>

despesas/app/views/responsibles/new.html.erb
<h1>Adicionar Responsavel</h1>
<br>
<%= render 'form' %>

<%= link_to 'Voltar', responsibles_path %>

despesas/app/views/responsibles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @responsible.name %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= @responsible.email %>
</p>

<%= link_to 'Editar', edit_responsible_path(@responsible) %> |
<%= link_to 'Voltar', responsibles_path %>

despesas/app/views/welcome/index.html.erb
<div align="center">
<h1>Pagina Inicial do Gerenciador de Despesas</h1> <br>
<%= link_to 'Controle de Responsaveis', '\responsibles' %> &nbsp
<%= link_to 'Controle de Despesas', '\bills' %>
</div>